# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 02:06
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200)),
                ('nick_name', models.CharField(blank=True, max_length=200, null=True)),
                ('facebook_full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('phone_number', models.IntegerField(blank=True, default=8052845564, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_of_birth', models.DateField()),
                ('race', models.CharField(choices=[('W', 'White'), ('AA', 'African American'), ('A', 'Asian'), ('AI', 'American Indian')], max_length=2)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('address', models.CharField(max_length=200)),
                ('state', localflavor.us.models.USStateField()),
                ('city', models.CharField(max_length=50)),
                ('zipcode', localflavor.us.models.USZipCodeField()),
            ],
        ),
    ]
