# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 02:13
from __future__ import unicode_literals

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=localflavor.us.models.PhoneNumberField(blank=True, default=8052845564, null=True),
        ),
    ]
